"""empty message

Revision ID: 07454cdd0a7c
Revises: 
Create Date: 2023-01-28 20:40:17.894877

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07454cdd0a7c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'user', ['user_name'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='unique')
    # ### end Alembic commands ###
