"""empty message

Revision ID: 38fcdb0b86b3
Revises: c2b32211b382
Create Date: 2022-12-06 05:43:24.786823

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '38fcdb0b86b3'
down_revision = 'c2b32211b382'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('despacho',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('documento', sa.BigInteger(), nullable=False),
    sa.Column('guia_despacho', sa.Integer(), nullable=False),
    sa.Column('b_origen_salida', sa.String(length=20), nullable=False),
    sa.Column('b_destino_salida', sa.String(length=20), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('f_despacho_fisico', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.create_table('embalado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=False),
    sa.Column('tipo_caja', sa.String(length=2), nullable=True),
    sa.Column('nro_caja', sa.Integer(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.create_table('empacado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=False),
    sa.Column('empacado', sa.Boolean(), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('empacado')
    op.drop_table('embalado')
    op.drop_table('despacho')
    # ### end Alembic commands ###
