"""empty message

Revision ID: 563b9cab2bed
Revises: e744deccd90c
Create Date: 2022-12-09 13:49:17.897855

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '563b9cab2bed'
down_revision = 'e744deccd90c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('salida', sa.Column('revision_movil_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'salida', 'revision_movil', ['revision_movil_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'salida', type_='foreignkey')
    op.drop_column('salida', 'revision_movil_id')
    # ### end Alembic commands ###
