"""empty message

Revision ID: 58e9942bdf4b
Revises: 854f042661fc
Create Date: 2022-12-05 18:05:45.147577

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58e9942bdf4b'
down_revision = '854f042661fc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('role', sa.Column('create_at', sa.Date(), nullable=True))
    op.add_column('user', sa.Column('create_at', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'create_at')
    op.drop_column('role', 'create_at')
    # ### end Alembic commands ###
