"""empty message

Revision ID: 854f042661fc
Revises: 689b0bc3f2ac
Create Date: 2022-12-03 04:35:16.647611

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '854f042661fc'
down_revision = '689b0bc3f2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('user', sa.Column('second_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('last_name', sa.String(length=100), nullable=False))
    op.add_column('user', sa.Column('second_last_name', sa.String(length=100), nullable=True))
    op.add_column('user', sa.Column('rut', sa.String(length=10), nullable=False))
    op.add_column('user', sa.Column('role_id', sa.Integer(), nullable=False))
    op.drop_index('name', table_name='user')
    op.create_unique_constraint(None, 'user', ['rut'])
    op.create_foreign_key(None, 'user', 'role', ['role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='unique')
    op.create_index('name', 'user', ['name'], unique=False)
    op.drop_column('user', 'role_id')
    op.drop_column('user', 'rut')
    op.drop_column('user', 'second_last_name')
    op.drop_column('user', 'last_name')
    op.drop_column('user', 'second_name')
    op.drop_table('role')
    # ### end Alembic commands ###
