"""empty message

Revision ID: 8f0c4803308e
Revises: b3b1388b2e33
Create Date: 2022-12-05 18:28:39.429166

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8f0c4803308e'
down_revision = 'b3b1388b2e33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recepcion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.BigInteger(), nullable=False),
    sa.Column('folio', sa.BigInteger(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=True),
    sa.Column('rut', sa.String(length=20), nullable=True),
    sa.Column('b_origen', sa.String(length=20), nullable=False),
    sa.Column('b_destino', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.add_column('maestro__series', sa.Column('denominacion', sa.String(length=100), nullable=False))
    op.drop_column('maestro__series', 'descripcion')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maestro__series', sa.Column('descripcion', mysql.VARCHAR(length=100), nullable=False))
    op.drop_column('maestro__series', 'denominacion')
    op.drop_table('recepcion')
    # ### end Alembic commands ###
