"""empty message

Revision ID: 8fb471fbcbf1
Revises: 8f0c4803308e
Create Date: 2022-12-05 18:52:38.443466

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fb471fbcbf1'
down_revision = '8f0c4803308e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('verificacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('f_verificacion', sa.Date(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('responsable', sa.String(length=10), nullable=False),
    sa.Column('tipo_caja', sa.String(length=2), nullable=True),
    sa.Column('nro_caja', sa.Integer(), nullable=True),
    sa.Column('estatus', sa.String(length=20), nullable=True),
    sa.Column('pedido', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('responsable'),
    sa.UniqueConstraint('serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('verificacion')
    # ### end Alembic commands ###
