"""empty message

Revision ID: b3b1388b2e33
Revises: b911dd8e19d8
Create Date: 2022-12-05 18:21:29.910888

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3b1388b2e33'
down_revision = 'b911dd8e19d8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bodega',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('tipo_caja', sa.String(length=2), nullable=True),
    sa.Column('nro_caja', sa.Integer(), nullable=True),
    sa.Column('estante', sa.Integer(), nullable=True),
    sa.Column('piso', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.add_column('maestro__series', sa.Column('serie', sa.BigInteger(), nullable=False))
    op.drop_index('imei', table_name='maestro__series')
    op.create_unique_constraint(None, 'maestro__series', ['serie'])
    op.drop_column('maestro__series', 'imei')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maestro__series', sa.Column('imei', mysql.BIGINT(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'maestro__series', type_='unique')
    op.create_index('imei', 'maestro__series', ['imei'], unique=False)
    op.drop_column('maestro__series', 'serie')
    op.drop_table('bodega')
    # ### end Alembic commands ###
