"""empty message

Revision ID: b911dd8e19d8
Revises: 58e9942bdf4b
Create Date: 2022-12-05 18:09:55.113043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b911dd8e19d8'
down_revision = '58e9942bdf4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maestro__series',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_entrada', sa.BigInteger(), nullable=False),
    sa.Column('folio', sa.BigInteger(), nullable=False),
    sa.Column('fecha_folio', sa.Date(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.Column('descripcion', sa.String(length=100), nullable=False),
    sa.Column('imei', sa.BigInteger(), nullable=False),
    sa.Column('b_origen_entrada', sa.String(length=20), nullable=False),
    sa.Column('b_destino_entrada', sa.String(length=20), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('fecha_verificacion', sa.Date(), nullable=True),
    sa.Column('estado_bodega', sa.String(length=20), nullable=False),
    sa.Column('estado_prod', sa.String(length=20), nullable=False),
    sa.Column('documento_salida', sa.BigInteger(), nullable=False),
    sa.Column('guia_despacho', sa.Integer(), nullable=False),
    sa.Column('b_origen_salida', sa.String(length=20), nullable=False),
    sa.Column('b_destino_salida', sa.String(length=20), nullable=False),
    sa.Column('fecha_despacho', sa.Date(), nullable=False),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('imei')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('maestro__series')
    # ### end Alembic commands ###
