"""empty message

Revision ID: c04fe6c93381
Revises: 
Create Date: 2022-12-09 19:09:17.906792

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c04fe6c93381'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('equipos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento_entrada', sa.BigInteger(), nullable=False),
    sa.Column('folio', sa.BigInteger(), nullable=False),
    sa.Column('fecha_folio', sa.Date(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('b_origen_entrada', sa.String(length=20), nullable=False),
    sa.Column('b_destino_entrada', sa.String(length=20), nullable=False),
    sa.Column('fecha_recepcion', sa.Date(), nullable=True),
    sa.Column('fecha_verificacion', sa.Date(), nullable=True),
    sa.Column('estado_bodega', sa.String(length=20), nullable=False),
    sa.Column('estado_prod', sa.String(length=20), nullable=False),
    sa.Column('documento_salida', sa.BigInteger(), nullable=False),
    sa.Column('guia_despacho', sa.Integer(), nullable=False),
    sa.Column('b_origen_salida', sa.String(length=20), nullable=False),
    sa.Column('b_destino_salida', sa.String(length=20), nullable=False),
    sa.Column('fecha_despacho', sa.Date(), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('tipo_caja', sa.String(length=2), nullable=True),
    sa.Column('nro_caja', sa.Integer(), nullable=True),
    sa.Column('estante', sa.Integer(), nullable=True),
    sa.Column('piso', sa.Integer(), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.create_table('role',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=250), nullable=True),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('entrada',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('documento', sa.BigInteger(), nullable=True),
    sa.Column('folio', sa.BigInteger(), nullable=True),
    sa.Column('fecha_folio', sa.Date(), nullable=True),
    sa.Column('material', sa.Integer(), nullable=True),
    sa.Column('denominacion', sa.String(length=100), nullable=True),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('rut_empresa', sa.String(length=20), nullable=True),
    sa.Column('b_origen', sa.String(length=20), nullable=True),
    sa.Column('b_destino', sa.String(length=20), nullable=True),
    sa.Column('f_recepcion_fisica', sa.Date(), nullable=True),
    sa.Column('f_verificacion', sa.Date(), nullable=True),
    sa.Column('responsable_ver', sa.String(length=10), nullable=True),
    sa.Column('tipo_caja', sa.String(length=2), nullable=True),
    sa.Column('nro_caja', sa.Integer(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.Column('observaciones', sa.String(length=250), nullable=True),
    sa.ForeignKeyConstraint(['serie'], ['equipos.serie'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('second_name', sa.String(length=100), nullable=True),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('second_last_name', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=250), nullable=False),
    sa.Column('rut', sa.String(length=10), nullable=False),
    sa.Column('create_at', sa.Date(), nullable=True),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['role.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('rut')
    )
    op.create_table('asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('id_asignacion', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('fecha_asignacion', sa.Date(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=True),
    sa.ForeignKeyConstraint(['serie'], ['equipos.serie'], ),
    sa.ForeignKeyConstraint(['tecnico_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id', 'id_asignacion', 'serie', 'tecnico_id')
    )
    op.create_table('revision_movil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('encendido', sa.Boolean(), nullable=True),
    sa.Column('frontal', sa.Boolean(), nullable=True),
    sa.Column('frontal_r', sa.Boolean(), nullable=True),
    sa.Column('trasera', sa.Boolean(), nullable=True),
    sa.Column('trasera_r', sa.Boolean(), nullable=True),
    sa.Column('superior', sa.Boolean(), nullable=True),
    sa.Column('superior_r', sa.Boolean(), nullable=True),
    sa.Column('inferior', sa.Boolean(), nullable=True),
    sa.Column('inferior_r', sa.Boolean(), nullable=True),
    sa.Column('izquierdo', sa.Boolean(), nullable=True),
    sa.Column('izquierdo_r', sa.Boolean(), nullable=True),
    sa.Column('derecho', sa.Boolean(), nullable=True),
    sa.Column('derecho_r', sa.Boolean(), nullable=True),
    sa.Column('puntaje_cos', sa.Integer(), nullable=True),
    sa.Column('pantalla', sa.Boolean(), nullable=True),
    sa.Column('tactil', sa.Boolean(), nullable=True),
    sa.Column('botones', sa.Boolean(), nullable=True),
    sa.Column('mic', sa.Boolean(), nullable=True),
    sa.Column('audio', sa.Boolean(), nullable=True),
    sa.Column('bateria', sa.Boolean(), nullable=True),
    sa.Column('conector_c', sa.Boolean(), nullable=True),
    sa.Column('bluetooth', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('zona_w', sa.Boolean(), nullable=True),
    sa.Column('nfc', sa.Boolean(), nullable=True),
    sa.Column('conector_a', sa.Boolean(), nullable=True),
    sa.Column('porta_sim', sa.Boolean(), nullable=True),
    sa.Column('filtracion', sa.Boolean(), nullable=True),
    sa.Column('llamadas_e', sa.Boolean(), nullable=True),
    sa.Column('llamadas_r', sa.Boolean(), nullable=True),
    sa.Column('msj_e', sa.Boolean(), nullable=True),
    sa.Column('msj_r', sa.Boolean(), nullable=True),
    sa.Column('foto_f', sa.Boolean(), nullable=True),
    sa.Column('foto_t', sa.Boolean(), nullable=True),
    sa.Column('video_f', sa.Boolean(), nullable=True),
    sa.Column('video_t', sa.Boolean(), nullable=True),
    sa.Column('sen_proximidad', sa.Boolean(), nullable=True),
    sa.Column('vibrador', sa.Boolean(), nullable=True),
    sa.Column('puntaje_tec', sa.Integer(), nullable=True),
    sa.Column('bloqueo', sa.Boolean(), nullable=True),
    sa.Column('act_sw', sa.Boolean(), nullable=True),
    sa.Column('restauracion', sa.Boolean(), nullable=True),
    sa.Column('fecha_rev', sa.Date(), nullable=True),
    sa.Column('clasificacion', sa.String(length=20), nullable=True),
    sa.Column('ert', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.String(length=100), nullable=True),
    sa.Column('id_asignacion', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_asignacion'], ['asignacion.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.create_table('salida',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=True),
    sa.Column('denominacion', sa.String(length=100), nullable=True),
    sa.Column('empacado', sa.Boolean(), nullable=True),
    sa.Column('fecha_empacado', sa.Date(), nullable=True),
    sa.Column('responsable_id', sa.Integer(), nullable=True),
    sa.Column('tipo_caja', sa.String(length=2), nullable=True),
    sa.Column('nro_caja', sa.Integer(), nullable=True),
    sa.Column('fecha_embalaje', sa.Date(), nullable=True),
    sa.Column('documento', sa.BigInteger(), nullable=True),
    sa.Column('guia_despacho', sa.Integer(), nullable=True),
    sa.Column('b_origen_salida', sa.String(length=20), nullable=True),
    sa.Column('b_destino_salida', sa.String(length=20), nullable=True),
    sa.Column('fecha_documento', sa.Date(), nullable=True),
    sa.Column('f_despacho_fisico', sa.Date(), nullable=True),
    sa.Column('revision_movil_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['revision_movil_id'], ['revision_movil.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('salida')
    op.drop_table('revision_movil')
    op.drop_table('asignacion')
    op.drop_table('user')
    op.drop_table('entrada')
    op.drop_table('role')
    op.drop_table('equipos')
    # ### end Alembic commands ###
