"""empty message

Revision ID: c2b32211b382
Revises: 8fb471fbcbf1
Create Date: 2022-12-06 05:22:00.654175

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c2b32211b382'
down_revision = '8fb471fbcbf1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asignacion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('check', sa.Boolean(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    op.create_table('movil',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serie', sa.BigInteger(), nullable=False),
    sa.Column('material', sa.Integer(), nullable=False),
    sa.Column('denominacion', sa.String(length=100), nullable=False),
    sa.Column('tecnico_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('encendido', sa.Boolean(), nullable=True),
    sa.Column('frontal', sa.Boolean(), nullable=True),
    sa.Column('frontal_r', sa.Boolean(), nullable=True),
    sa.Column('trasera', sa.Boolean(), nullable=True),
    sa.Column('trasera_r', sa.Boolean(), nullable=True),
    sa.Column('superior', sa.Boolean(), nullable=True),
    sa.Column('superior_r', sa.Boolean(), nullable=True),
    sa.Column('inferior', sa.Boolean(), nullable=True),
    sa.Column('inferior_r', sa.Boolean(), nullable=True),
    sa.Column('izquierdo', sa.Boolean(), nullable=True),
    sa.Column('izquierdo_r', sa.Boolean(), nullable=True),
    sa.Column('derecho', sa.Boolean(), nullable=True),
    sa.Column('derecho_r', sa.Boolean(), nullable=True),
    sa.Column('puntaje_cos', sa.Integer(), nullable=True),
    sa.Column('pantalla', sa.Boolean(), nullable=True),
    sa.Column('tactil', sa.Boolean(), nullable=True),
    sa.Column('botones', sa.Boolean(), nullable=True),
    sa.Column('mic', sa.Boolean(), nullable=True),
    sa.Column('audio', sa.Boolean(), nullable=True),
    sa.Column('bateria', sa.Boolean(), nullable=True),
    sa.Column('conector_c', sa.Boolean(), nullable=True),
    sa.Column('bluetooth', sa.Boolean(), nullable=True),
    sa.Column('wifi', sa.Boolean(), nullable=True),
    sa.Column('zona_w', sa.Boolean(), nullable=True),
    sa.Column('nfc', sa.Boolean(), nullable=True),
    sa.Column('conector_a', sa.Boolean(), nullable=True),
    sa.Column('porta_sim', sa.Boolean(), nullable=True),
    sa.Column('filtracion', sa.Boolean(), nullable=True),
    sa.Column('llamadas_e', sa.Boolean(), nullable=True),
    sa.Column('llamadas_r', sa.Boolean(), nullable=True),
    sa.Column('msj_e', sa.Boolean(), nullable=True),
    sa.Column('msj_r', sa.Boolean(), nullable=True),
    sa.Column('foto_f', sa.Boolean(), nullable=True),
    sa.Column('foto_t', sa.Boolean(), nullable=True),
    sa.Column('video_f', sa.Boolean(), nullable=True),
    sa.Column('video_t', sa.Boolean(), nullable=True),
    sa.Column('sen_proximidad', sa.Boolean(), nullable=True),
    sa.Column('vibrador', sa.Boolean(), nullable=True),
    sa.Column('puntaje_tec', sa.Integer(), nullable=True),
    sa.Column('bloqueo', sa.Boolean(), nullable=True),
    sa.Column('act_sw', sa.Boolean(), nullable=True),
    sa.Column('restauracion', sa.Boolean(), nullable=True),
    sa.Column('fecha_rev', sa.Date(), nullable=True),
    sa.Column('clasificacion', sa.String(length=20), nullable=True),
    sa.Column('ert', sa.Boolean(), nullable=True),
    sa.Column('observaciones', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('serie')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movil')
    op.drop_table('asignacion')
    # ### end Alembic commands ###
